ALTER TABLE `Discussion`
    ADD COLUMN `status` ENUM('OPEN','ASSIGNED','CLOSED') NOT NULL DEFAULT 'OPEN';

ALTER TABLE `Message`
    ADD COLUMN `authorRole` ENUM('CLIENT','ADVISOR') NOT NULL DEFAULT 'CLIENT';
